import { Language } from '../types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    appTitle: 'Navratri Ahmedabad',
    tagline: 'Garba, Dineout, Passes & Live Vibes',
    venuesTab: 'Garba Venues',
    dineoutTab: 'Late Dineout',
    passesTab: 'My Passes',
    liveFeedTab: 'Live Feed',
    navMapTab: 'Navigation',
    adminTab: 'Admin Desk',
    aiStudioBtn: 'AI Festive Studio',
    aiChatBtn: 'Ask RaasGuru AI',
    searchVenues: 'Search venues, artist, pol, or zone in Ahmedabad...',
    filterAll: 'All Venues',
    filterMega: 'Mega Grounds',
    filterClub: 'Clubs & VIP',
    filterHeritage: 'Heritage Pol',
    crowdChill: 'Chill (Low)',
    crowdModerate: 'Moderate',
    crowdHigh: 'High Crowd',
    crowdPacked: 'Peak Packed',
    liveDensity: 'Live Crowd Density',
    entryFee: 'Entry Pass',
    seasonPass: 'Season Pass',
    bookPass: 'Book Digital Pass',
    viewDetails: 'View Ground Details',
    parkingAvail: 'Parking Available',
    parkingFull: 'Parking Almost Full',
    sheTeamActive: 'Ahmedabad Police SHE-Team Active',
    reserveTable: 'Reserve Table',
    openTill: 'Open till',
    priceForTwo: 'Cost for two',
    signatureBites: 'Signature Midnight Bites',
    postGarbaSnacks: 'Ahmedabad Late-Night Post-Garba Dining',
    offlineStatus: 'Offline Protected Mode',
    onlineStatus: 'Live Real-time Sync',
    simOffline: 'Simulate Offline',
    simOnline: 'Switch to Live',
    emergencySOS: 'Emergency SOS / Police',
    biometricVault: 'Biometric Secure Vault',
    notifications: 'Notifications',
    guestCount: 'Guests',
    selectSlot: 'Select Midnight Slot',
    confirmBooking: 'Confirm Reservation',
    downloadReport: 'Export Analytics (CSV)',
    totalDancers: 'Dancers on Ground Tonight',
    activeVenues: 'Tracked Ahmedabad Grounds',
    tableBookings: 'Table Bookings Tonight',
  },
  gu: {
    appTitle: 'નવરાત્રિ અમદાવાદ',
    tagline: 'ગરબા, ડાઇનઆઉટ, ડિજિટલ પાસ અને લાઇવ વાઇબ્સ',
    venuesTab: 'ગરબા સ્થળો',
    dineoutTab: 'લેટ ડાઇનઆઉટ',
    passesTab: 'મારા પાસ',
    liveFeedTab: 'લાઇવ ફીડ',
    navMapTab: 'નેવિગેશન',
    adminTab: 'એડમિન ડેસ્ક',
    aiStudioBtn: 'AI ફેસ્ટિવ સ્ટુડિયો',
    aiChatBtn: 'રાસગુરુ AI ને પૂછો',
    searchVenues: 'અમદાવાદમાં સ્થળ, કલાકાર, પોળ અથવા ઝોન શોધો...',
    filterAll: 'બધા સ્થળો',
    filterMega: 'મેગા ગ્રાઉન્ડ્સ',
    filterClub: 'ક્લબ્સ અને વીઆઇપી',
    filterHeritage: 'હેરિટેજ શેરી પોળ',
    crowdChill: 'શાંત (ઓછી ભીડ)',
    crowdModerate: 'મધ્યમ ભીડ',
    crowdHigh: 'વધારે ભીડ',
    crowdPacked: 'હાઉસફુલ / પીક',
    liveDensity: 'લાઇવ ભીડ ઘનતા',
    entryFee: 'એન્ટ્રી પાસ',
    seasonPass: 'સીઝન પાસ (૯ રાત)',
    bookPass: 'ડિજિટલ પાસ બુક કરો',
    viewDetails: 'ગ્રાઉન્ડ વિગત જુઓ',
    parkingAvail: 'પાર્કિંગ ઉપલબ્ધ છે',
    parkingFull: 'પાર્કિંગ લગભગ ભરેલું છે',
    sheTeamActive: 'અમદાવાદ પોલીસ SHE-Team તૈનાત',
    reserveTable: 'ટેબલ બુક કરો',
    openTill: 'ખુલ્લું છે',
    priceForTwo: 'બે વ્યક્તિનો ખર્ચ',
    signatureBites: 'પ્રખ્યાત મધ્યરાત્રિ વાનગીઓ',
    postGarbaSnacks: 'ગરબા પછી અમદાવાદનું પ્રખ્યાત મધ્યરાત્રિ ભોજન',
    offlineStatus: 'ઑફલાઇન સંરક્ષિત મોડ',
    onlineStatus: 'લાઇવ રીઅલ-ટાઇમ સિંક',
    simOffline: 'ઑફલાઇન ટેસ્ટ કરો',
    simOnline: 'લાઇવ મોડ ચાલુ કરો',
    emergencySOS: 'ઇમરજન્સી SOS / પોલીસ સહાય',
    biometricVault: 'બાયોમેટ્રિક સિક્યોર વૉલ્ટ',
    notifications: 'સૂચનાઓ',
    guestCount: 'મહેમાનો',
    selectSlot: 'મધ્યરાત્રિ સમય પસંદ કરો',
    confirmBooking: 'બુકિંગ કન્ફર્મ કરો',
    downloadReport: 'રિપોર્ટ એક્સપોર્ટ (CSV)',
    totalDancers: 'આજે રાત્રે મેદાન પર ખેલૈયાઓ',
    activeVenues: 'અમદાવાદના સક્રિય ગ્રાઉન્ડ્સ',
    tableBookings: 'આજની ટેબલ રિઝર્વેશન',
  },
  hi: {
    appTitle: 'नवरात्रि अहमदाबाद',
    tagline: 'गरबा, डाइनआउट, डिजिटल पास और लाइव वाइब्स',
    venuesTab: 'गरबा स्थल',
    dineoutTab: 'लेट डाइनआउट',
    passesTab: 'मेरे पास',
    liveFeedTab: 'लाइव फीड',
    navMapTab: 'नेविगेशन',
    adminTab: 'एडमिन डेस्क',
    aiStudioBtn: 'AI फेस्टिव स्टूडियो',
    aiChatBtn: 'रासगुरु AI से पूछें',
    searchVenues: 'अहमदाबाद में स्थल, कलाकार, पोल या ज़ोन खोजें...',
    filterAll: 'सभी स्थल',
    filterMega: 'मेगा ग्राउंड्स',
    filterClub: 'क्लब्स और वीआईपी',
    filterHeritage: 'हेरिटेज पोल',
    crowdChill: 'शांत (कम भीड़)',
    crowdModerate: 'मध्यम भीड़',
    crowdHigh: 'ज्यादा भीड़',
    crowdPacked: 'हाउसफुल / पीक',
    liveDensity: 'लाइव भीड़ घनत्व',
    entryFee: 'एंट्री पास',
    seasonPass: 'सीज़न पास',
    bookPass: 'डिजिटल पास बुक करें',
    viewDetails: 'ग्राउंड विवरण देखें',
    parkingAvail: 'पार्किंग उपलब्ध है',
    parkingFull: 'पार्किंग लगभग फुल',
    sheTeamActive: 'अहमदाबाद पुलिस SHE-Team तैनात',
    reserveTable: 'टेबल रिज़र्व करें',
    openTill: 'खुला रहेगा',
    priceForTwo: 'दो लोगों का खर्च',
    signatureBites: 'खास मिडनाइट व्यंजन',
    postGarbaSnacks: 'गरबा के बाद अहमदाबाद का प्रसिद्ध मिडनाइट भोजन',
    offlineStatus: 'ऑफ़लाइन सुरक्षित मोड',
    onlineStatus: 'लाइव रीयल-टाइम सिंक',
    simOffline: 'ऑफ़लाइन टेस्ट करें',
    simOnline: 'लाइव मोड चालू करें',
    emergencySOS: 'आपातकालीन SOS / पुलिस',
    biometricVault: 'बायोमेट्रिक सिक्योर वॉल्ट',
    notifications: 'सूचनाएं',
    guestCount: 'अतिथि',
    selectSlot: 'मिडनाइट स्लॉट चुनें',
    confirmBooking: 'बुकिंग कन्फर्म करें',
    downloadReport: 'रिपोर्ट एक्सपोर्ट (CSV)',
    totalDancers: 'आज रात मैदान पर खिलाड़ी',
    activeVenues: 'ट्रैक किए गए अहमदाबाद ग्राउंड्स',
    tableBookings: 'आज की टेबल बुकिंग',
  },
};
